# Generated by Django 4.2.7 on 2025-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20251224_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='avatar',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
