# Generated by Django 4.2.7 on 2026-01-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_avatar_blogpost_comments_and_more'),
    ]

    operations = [
    ]
