# Generated by Django 4.2.7 on 2025-12-24 02:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_created_at_and_more'),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=30),
        ),
        migrations.CreateModel(
            name='BlockchainPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_payment', to='orders.order')),
                ('wallet_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_link', to='blockchain.walletpayment')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
